AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Template stack for NVA monitoring

Parameters:
  NvaMonitoringDashBoardName:
    Type: 'String'
    Default: 'NvaMonitoringDashboard'
    Description: Name monitoring dashboard that will be updated by this lambda
  SlackSnsArn:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/NVA/Monitoring/SlackSnsArn'

Resources:

  UpdateDashboardHandlerLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      RetentionInDays: 30
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref UpdateDashboardHandler]]

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole


  DefaultLambdaPermissions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub DefaultLambdaPermissions-${AWS::StackName}
      Roles:
        - !Ref LambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogGroups
              - lambda:InvokeFunction
              - lambda:ListFunctions
            Resource: "*"

  CloudWatchPermissions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub CloudWatchPermissions-${AWS::StackName}
      Roles:
        - !Ref LambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - cloudwatch:GetDashboard
              - cloudwatch:PutDashboard
              - cloudwatch:DescribeAlarms
            Resource: "*"

  ApiGatewayPermissions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub ApiGatewayPermissions-${AWS::StackName}
      Roles:
        - !Ref LambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - Apigateway:GET
            Resource: "*"


  UpdateDashboardHandler:
    Type: AWS::Serverless::Function
    DependsOn:
      - DefaultLambdaPermissions
      - CloudWatchPermissions
      - ApiGatewayPermissions
    Properties:
      CodeUri: dashboard
      Handler: no.sikt.nva.monitoring.UpdateDashboardHandler::handleRequest
      Timeout: 900
      Runtime: java21
      Role: !GetAtt LambdaRole.Arn
      MemorySize: 1800
      Environment:
        Variables:
          DASHBOARD_NAME: !Sub "${NvaMonitoringDashBoardName}-${AWS::AccountId}"
      Events:
        StackEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - "aws.cloudformation"
              detail-type:
                - "AWS API Call via CloudTrail"
              detail:
                eventSource:
                  - "cloudformation.amazonaws.com"
                eventName:
                  - "CreateStack"
                  - "UpdateStack"
                  - "DeleteStack"

  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub "${NvaMonitoringDashBoardName}-${AWS::AccountId}"
      DashboardBody: "{\"widgets\":[]}"


  CostAnomalySubscription:
    Type: "AWS::CE::AnomalySubscription"
    Properties:
      Frequency: "IMMEDIATE"
      MonitorArnList:
        - !Ref CostAnomalyMonitor
      Subscribers:
        - Address: !Ref SlackSnsArn
          Type: "SNS"
      Threshold: 100.0
      SubscriptionName: "Cost Anomaly Subscription"

  CostAnomalyMonitor:
    Type: "AWS::CE::AnomalyMonitor"
    Properties:
      MonitorName: "Cost Anomaly Monitor"
      MonitorType: "DIMENSIONAL"
      MonitorDimension: "SERVICE"

  CloudWatchAlarm:
    Type: "AWS::CloudWatch::Alarm"
    Properties:
      AlarmName: "CostAnomalyAlarm"
      AlarmDescription: "Alarm for Cost Anomaly Detection"
      MetricName: "AnomalyDetection"
      Namespace: "AWS/CostExplorer"
      Statistic: "Maximum"
      Period: 600  # Check every 10 minutes
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: "GreaterThanOrEqualToThreshold"
