[versions]
awsSdk2 = { strictly = '2.23.12' }
log4j = { strictly = '2.22.1' }
slf4j = { strictly = '2.0.11' }


[libraries]


aws-core = { group = 'software.amazon.awssdk', name = 'aws-core', version.ref = 'awsSdk2' }



slf4j = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }
log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4j' }






