[versions]
log4j = { strictly = '2.23.0' }
slf4j = { require = '2.0.12' }
awsLambdaCore = { strictly = '1.2.3' }
awsLambdaEvents = { strictly = '3.11.4' }


[libraries]

aws-lambda-java-core = { group = 'com.amazonaws', name = 'aws-lambda-java-core', version.ref = 'awsLambdaCore' }
aws-lambda-events = { group = 'com.amazonaws', name = 'aws-lambda-java-events', version.ref = 'awsLambdaEvents' }




log4j-core = { group = 'org.apache.logging.log4j', name = 'log4j-core', version.ref = 'log4j' }
log4j-api = { group = 'org.apache.logging.log4j', name = 'log4j-api', version.ref = 'log4j' }
log4j-slf4j-impl = { group = 'org.apache.logging.log4j', name = 'log4j-slf4j2-impl', version.ref = 'log4j' }
slf4j-api = { group = 'org.slf4j', name = 'slf4j-api', version.ref = 'slf4j' }

[bundles]
logging = ['log4j-core', 'log4j-api', 'log4j-slf4j-impl', 'slf4j-api']





